version: '3.4'

services:
  weightlosstracker.api:
    image: weightlosstracker.api:latest
    depends_on:
     - "postgres_image"
    build:
      context: .
      dockerfile: ../WeightLossTracker.Api/Dockerfile
    ports:
      - '1234:1233'
    environment:
      DefaultConnection__ConnectionString: "host=postgres_image;port=5432;username=sa;password=Password@1;database=dietTrackerdb"
    restart: on-failure
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    expose:  
      - 5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password@1
      POSTGRES_DB: "dietTrackerdb"
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local